### ISSUE TITLE
Intergate streaming plugin with annotation plugin.

### ISSUE THREAD

**Issue by bboyz269** [nagix/chartjs-plugin-streaming#1]
Hi, your plugin is very neat and useful. Thanks for the effort!
As I'm trying to create a real time data control chart. I'm using your plugin for streaming data and annotation plugin to draw UCL & LCL (Upper Control Limit & Lower Control Limit) lines. The problem is that when the chart is moved to the left, the annotation lines, which must be static, are moved as well. Screenshot attached below.
![Annotations are moved](https://user-images.githubusercontent.com/4453811/27668202-e0089948-5ca9-11e7-96d4-ccbfa20c240a.png)
Is it possible to make the annotation lines static just like the axises? Thanks in advance!

**Comment by nagix** [comment]
Thanks for trying the plugin!
As chartjs-plugin-streaming moves every element in a chart, the annotation lines and labels are also moved. A workaround at this moment is:

1. Include `chartjs-plugin-streaming.js` before `chartjs-plugin-annotation.js`
```
<script src="chartjs-plugin-streaming.js"></script>
<script src="chartjs-plugin-annotation.js"></script>
```

2. And, use `'afterDraw'` for `annotation.drawTime` and `annotation.annotations[*].drawTime`

This will solve your problem. I will investigate how to fix in the other cases.

**Comment by bboyz269** [comment]
Work perfectly! Thank you again!
