### ISSUE TITLE
Can't place more than one streaming chart on a single page.

### ISSUE THREAD

**Issue by david-streamlio** [nagix/chartjs-plugin-streaming#10]
If I modify the streaming example to host 2 charts, the UI jitters horribly.
[index.txt](https://github.com/nagix/chartjs-plugin-streaming/files/1696418/index.txt)

**Comment by nagix** [comment]
I don't see any UI jitters on my MacBook. On what device are you testing it? May be we'd better introduce the frame-per-second rendering option to save CPU resources.

**Comment by nagix** [comment]
With f1e773e, `frameRate` option was introduced. Please try to set it to a low value (frame-per-second) if you draw charts on a resource limited device. See this sample: https://jsfiddle.net/nagix/wgswzor3/. I also recommend to disable animation as stated at [Chart.js docs](http://www.chartjs.org/docs/latest/charts/line.html#disable-animations).
