### ISSUE TITLE
Warning: time scale: "time.format" is deprecated with chart.js 2.9.3

### ISSUE THREAD

**Issue by spoon252** [nagix/chartjs-plugin-streaming#100]
Hi,

I used this plugin for some time and it worked flawlessly. Recently these warnings started to appear.

time scale: "time.format" is deprecated. Please use "time.parser" instead

I think the library needs an update regarding this. I saw that Chart.js updated the "zoom" plugin because of same issue. Am I right?

**Comment by spoon252** [comment]
PR 98 solves this!

**Comment by shtomik** [comment]
> PR 98 solves this!

Hi, how do you solve this issue? What is PR 98? Thanks.
