### ISSUE TITLE
Chartjs 2.9.x support 

### ISSUE THREAD

**Issue by furkandoganktf** [nagix/chartjs-plugin-streaming#103]
When the support of chart.js 2.9.x will come, because when we use real-time plugin with the chart.js 2.9.3 the time axis is not sliding instead it is blinking when it moves to the left.

**Comment by Yahav** [comment]
Well, this is opened now for an year or so, wouldn't hold my breath...

**Comment by nagix** [comment]
Closing as the [version 1.9.0](https://github.com/nagix/chartjs-plugin-streaming/releases/tag/v1.9.0) that supports Chart.js 2.9.x was just released.
