### ISSUE TITLE
The x axis not moving

### ISSUE THREAD

**Issue by gajulan** [nagix/chartjs-plugin-streaming#106]
Im trying to make this chart
but it the x axis wont moving like the examples

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.js"></script>
	<script src="vendor/moment.js"</script>
	<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-streaming@latest/dist/chartjs-plugin-streaming.min.js"></script>

i already add the js to my file.
Any help?

**Comment by juliankigwana** [comment]
How did you fix it?

**Comment by phanuphongs** [comment]
I fixed it by down grade lib to version 1.8.0
