### ISSUE TITLE
Angular2 Push Model (Listening Based) 

### ISSUE THREAD

**Issue by wwjd1234** [nagix/chartjs-plugin-streaming#108]
Ho do you call the update method when using the attribute directive?

You have "baseChart" but do I need a reference to it to call update?

I am using a websocket.

**Comment by nagix** [comment]
If you are using [ng2-charts](https://valor-software.com/ng2-charts/), You can get a `BaseChartDirective` using `@ViewChild`, then use the `chart` property to set the data and call `update()`.

```typescript
import { Component, ViewChild } from '@angular/core';
import { BaseChartDirective } from 'ng2-charts';

export class AppComponent {
  @ViewChild(BaseChartDirective) chart: BaseChartDirective;

  update() {
    this.chart.chart.data.datasets.forEach((dataset: any) => {
      dataset.data.push({
        x: Date.now(),
        y: Math.random()
      });
    });
    this.chart.chart.update({duration: 0});
  }

  /* ... */
}
```
