### ISSUE TITLE
How can draw  Chart with float time and data

### ISSUE THREAD

**Issue by williamesp2015** [nagix/chartjs-plugin-streaming#11]
I could draw streaming ChartJs with integer but I need like ChartJs draw float numbers for X and Y axes.

**Comment by nagix** [comment]
Do you mean you want to set float numbers for the time scale axis?

If you set the `realtime` scale to X-axis and the `linear` scale to Y-axis, you can use float numbers for Y-axis values with the current version.

**Comment by williamesp2015** [comment]
Thanks. How I can show 32 bit float point for both X and Y ? Like x:1.245 msec, Y:0.0012

**Comment by nagix** [comment]
Moment.js, which is used in Chart.js, only supports milliseconds as the finest unit, so you cannot use float numbers to represent milliseconds values for X-axis.
