### ISSUE TITLE
One of the examples is broken

### ISSUE THREAD

**Issue by 7ruth** [nagix/chartjs-plugin-streaming#111]
Hello, the financial example at this url doesnt seem to render: 

https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html

**Comment by nagix** [comment]
The [version 2.0.0-beta.1](https://github.com/nagix/chartjs-plugin-streaming/releases/tag/v2.0.0-beta.1) was just released, and it supports the latest version of chartjs-chart-financial. The [sample chart](https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html) was also updated.
