### ISSUE TITLE
Push Model (Listening Based) with reatime?

### ISSUE THREAD

**Issue by teixeirel** [nagix/chartjs-plugin-streaming#114]
Hello, 
I am using push model to work with firebase and it's work fine. I receive timestamp and value from there.
But now, I am trying to implement **realtime: {duration: 20000}** to visualize an window of 20 seconds and delete old data like the example https://nagix.github.io/chartjs-plugin-streaming/samples/zoom.html. Is this possible to do with push model?
Regards!

**Comment by dougjedwards** [comment]
@teixeirel Did you manage to get this right?

**Comment by teixeirel** [comment]
Yes

**Comment by nagix** [comment]
The answer is yes. Closing as this seems to have been resolved.
