### ISSUE TITLE
Using with chartjs-chart-financial.js

### ISSUE THREAD

**Issue by ArtemBondarenko1997** [nagix/chartjs-plugin-streaming#117]
Hello,I need to use your plugin in conjunction with chartjs-chart-financial.js. But when I use the code from the example, I get the following error: Cannot read property 'bar' of undefined
     at chartjs-chart-financial.js: 378
Thanks !

![image](https://user-images.githubusercontent.com/32524801/79991529-14be7b80-84bb-11ea-915b-529b1b4b587e.png)

**Comment by maxim-s-barabash** [comment]
same error in example
https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html

**Comment by cuongnghiem** [comment]
Anybody fix it?

**Comment by carlitoselmago** [comment]
same problem

**Comment by nagix** [comment]
The [version 2.0.0-beta.1](https://github.com/nagix/chartjs-plugin-streaming/releases/tag/v2.0.0-beta.1) was just released, and it supports the latest version of chartjs-chart-financial. See the [sample chart](https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html).
