### ISSUE TITLE
requestAnimationFrame should be used instead of fixed update interval.

### ISSUE THREAD

**Issue by ferdinandschober** [nagix/chartjs-plugin-streaming#125]
the scrolling of the graph is very stuttery which could be greatly improved by using the [requestAnimationFrame](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame)() callback instead of a fixed framerate.

**Comment by nagix** [comment]
This plugin is actually using `requestAnimationFrame` callback through the [`requestAnimFrame`](https://github.com/chartjs/Chart.js/blob/938865f67d35331e00b21a39825b607aa660fa14/src/helpers/helpers.extras.js#L9-L16) helper function in Chart.js. For better performance, the frame rate is set to 30 by default, which results in skipping half of the frames, but you may see smoother scrolling if you set the `frameRate` option to 60.
