### ISSUE TITLE
Chartjs 3.x.x support

### ISSUE THREAD

**Issue by kevinoo** [nagix/chartjs-plugin-streaming#126]
Hi everyone,
waiting for the official ChartJS 3.0 version to be released: I have developed support for this plugin.

- Chartjs required v3.x.x
- Chartjs-plugin-streaming v2.0  :smile: 

[Link to Chartjs-plugin-streaming v2.0](https://github.com/kevinoo/chartjs-plugin-streaming)

I hope I did something pleasant :smile:

**Comment by jinyanghuang** [comment]
Hi, does the install instruction remain the same?

**Comment by kevinoo** [comment]
Hi @jinyanghuang,
at the moment the install of script is allow only with "script tag". 

I will try to activate other types of installation in the coming days.

**Comment by flieks** [comment]
I am also interested. Thanks
Using this with Chart.js v2.9.4 or latest react-chart-js but having the tick scrolling issue now
https://github.com/nagix/chartjs-plugin-streaming/issues/123

**Comment by omerg206** [comment]
HI @kevinoo can you provide an example how to import/install using the script tag/other methods?

**Comment by kevinoo** [comment]
Hi @omerg206 
unfortunately due to lack of time, I was unable to follow the project doing it installable with other types.

Sorry guys  🙏

**Comment by kevinoo** [comment]
@all

**UPDATE**

I was able to publish a beta version on npm, however it is not compatible with the latest release ChartJS v3.2.0.
I'm trying to understand why there is this problem (which was not there in beta10)

**Comment by kevinoo** [comment]
Hi all 😄 

I am happy to inform you that I have proceeded to publish the v2.1 version   

You can install it through **npm** or download it from **cdn**.

**Comment by nagix** [comment]
Closing as the [version 2.0.0-beta.1](https://github.com/nagix/chartjs-plugin-streaming/releases/tag/v2.0.0-beta.1 ) that supports Chart.js 3.x was just released.
