### ISSUE TITLE
Data labels overflow from the main chart area.

### ISSUE THREAD

**Issue by iamkryptonite** [nagix/chartjs-plugin-streaming#130]
On adding the data-label plugin, the data moves out from the main chart area
 and overlaps with the axis.
![Document](https://user-images.githubusercontent.com/43510609/113100211-bcd6db80-9218-11eb-81e1-14df8bff9c40.png)

**Comment by nagix** [comment]
You can use the [`clip` option](https://chartjs-plugin-datalabels.netlify.app/guide/positioning.html#clipping) in chartjs-plugin-datalabels to mask the part of the label which is outside the chart area.
