### ISSUE TITLE
Error : Cannot read property 'duration' of undefined chartjs-plugin-streaming

### ISSUE THREAD

**Issue by farshidpg** [nagix/chartjs-plugin-streaming#14]
hi , im trying update to new  version 1.3  after replace code  i have this error 

Uncaught TypeError: Cannot read property 'duration' of undefined chartjs-plugin-streaming

chartjs-plugin-streaming : 1.3
Chartjs : 2.7.2

**Comment by nagix** [comment]
This happens because Chart.js 2.7.2 changed the way it updates scale options internally. I will fix this shortly, so please use 2.7.1 for the moment.
