### ISSUE TITLE
Error on calling destroy()

### ISSUE THREAD

**Issue by schlunsen** [nagix/chartjs-plugin-streaming#15]
Hi,

I get following error message when calling destroy() on a graph using this plugin

![image](https://user-images.githubusercontent.com/117190/37370008-3365463c-270b-11e8-80e8-6d73ef94a956.png)

Thanks for a great project!

**Comment by nagix** [comment]
Thank you for reporting this issue. This happens because an internal interval timer is still running even after a chart is destroyed. I will fix it shortly.

**Comment by Spogge** [comment]
I love your chartjs plugin! When do plan to release v1.5.0 with the destroy() fix? It would be great to have.

Thanks!

**Comment by nagix** [comment]
v1.4.1 with this fix was just released.
