### ISSUE TITLE
Create array of data and then refresh chart

### ISSUE THREAD

**Issue by williamesp2015** [nagix/chartjs-plugin-streaming#17]
Is there a way to refresh chart periodically when data is coming fast from a client in a lets say Inputmessage() and can save data on a two dimensional array (Data[row][column])?

**Comment by nagix** [comment]
Is the code below useful for you? `inputMessage()` is a callback function which can be called more frequently then `onRefresh()` and receives a timestamp and an array of values. `refresh()` is to be set to the `options.plugins.streaming.onRefresh` option and updates data from the previous refresh.
```javascript
var timestamps = []; // timestamp array
var data = []; // two dimensional array (data[row][column])
var cursor = 0; // next refreshing row

// receive data from a client
function inputMessage(unix_timestamp, values) {
  timestamps.push(unix_timestamp);
  data.push(values);
}

// refresh function to be set to options.plugins.streaming.onRefresh option 
function refresh(chart) {
  length = data.length;
  Array.prototype.push.apply(
    chart.data.labels, timestamps.slice(cursor, length)
  };
  for (int i = cursor; i < length; i++) {
    for (int j = 0; j < data[i].length; j++) {
      chart.data.datasets[j].data.push(data[i][j]);
    }
  )
  cursor = length;
}
```

**Comment by williamesp2015** [comment]
Thanks. It would be very nice if you add an full example of a fast vertical line chart. I see some errors in the code.

**Comment by nagix** [comment]
I have fixed the code above and created a working example: https://jsfiddle.net/nagix/pfgr928v/.
