### ISSUE TITLE
Able to stop chart from scrolling (pause)

### ISSUE THREAD

**Issue by junelson89** [nagix/chartjs-plugin-streaming#20]
Hello, 

I've been using your plugin for a week and it's awesome. I am currently investigating ways on "pausing" the chart scrolling, stopping all updates to the chart data at the same time. Stopping the Ingress of data is easy, but I can't find a straightforward way to stop the automatic scrolling of the chart so I can peruse a subset of the data without it vanishing on me. 

Please advise. 

Thanks in advance, 

Jordan

**Comment by nagix** [comment]
As scrolling in the realtime scale is not an animation, `chart.stop()` has no effect, but the code below is a workaround for pause and resume of scrolling. Note that you need the recent fix in 9b42c55.

```
var chart = new Chart(ctx, config);
var streamingOpts;

function pause() {
    var scale = chart.scales['x-axis-0'];
    streamingOpts = chart.options.plugins.streaming;
    chart.options.scales.xAxes[0].type = 'time';
    chart.options.scales.xAxes[0].time.min = scale.min;
    chart.options.scales.xAxes[0].time.max = scale.max;
    chart.options.plugins.streaming = false;
    chart.update(0);
    scale.destroy();
}

function resume() {
    chart.options.scales.xAxes[0].type = 'realtime';
    chart.options.plugins.streaming = streamingOpts;
    chart.update(0);
}
```

**Comment by junelson89** [comment]
Thanks @nagix 

I'm using Angular5 and so far I'm unable to get this fix to work.

**Comment by junelson89** [comment]
Additionally, I rebuild the project using the latest from Chartjs and was able to run the demo application in my development environment. I have confirmed that I do have the code address in the merge request you specified. 

When I attempt to use pause and resume I get 'ERROR TypeError: scale.destroy is not a function'

**Comment by nagix** [comment]
Please try `nom install chartjs-plugin-streaming@1.4.1`. This version includes the fix, and I have confirmed this works with Angular 5.

**Comment by nagix** [comment]
Finally I have added the pause feature. Use the new option `plugins.streaming.pause` to pause and resume scrolling:
```
// pause
chart.options.plugins.streaming.pause = true;
chart.update();

// resume
chart.options.plugins.streaming.pause = false;
chart.update();
```

**Comment by venkatesh-nagineni** [comment]
Have you tested with latest version. I did that but my chart still scrolling continuously and i have checked `chart.options.plugins.streaming.pause` it shows `true`. Can you please test it again with angular 6.

**Comment by nagix** [comment]
@venkatesh-nagineni If you are using ng2-charts, valor-software/ng2-charts#291 might be a workaround.

**Comment by venkatesh-nagineni** [comment]
Thank you @nagix for your quick reply `this.chart.chart.update();` this rid of my syntax error but still i can't pause my chart.

**Comment by nagix** [comment]
@venkatesh-nagineni Please try this: https://stackoverflow.com/questions/51078798/pause-horizontal-scrolling-in-chart-js-for-real-time-data

**Comment by iamkryptonite** [comment]
> Finally I have added the pause feature. Use the new option `plugins.streaming.pause` to pause and resume scrolling:
> 
> ```
> // pause
> chart.options.plugins.streaming.pause = true;
> chart.update();
> 
> // resume
> chart.options.plugins.streaming.pause = false;
> chart.update();
> ```

This is amazing, thanks a lot for this. After resuming the chart scrolls to the current data,i.e current time, hence a lot of data values are missed in between. Is there a way to keep scrolling the chart from where it was paused?
