### ISSUE TITLE
Error when using in Internet Explorer 11

### ISSUE THREAD

**Issue by Jea-Eok-Kim** [nagix/chartjs-plugin-streaming#21]
If you are using Internet Explorer 11, the graph will disappear when you mouse-over the graph.

![20180329_110402](https://user-images.githubusercontent.com/35481922/38066124-9d509596-3341-11e8-93cb-cd837752b384.png)
![20180329_110436](https://user-images.githubusercontent.com/35481922/38066125-9d7b2702-3341-11e8-9f44-7efcddd8ce5d.png)

**Comment by nagix** [comment]
Thank you for reporting this issue. The error occurs when the plugin dispatches mouse events, and IE requires a different way to do that. I will fix it shortly.

**Comment by gadian88** [comment]
Thank you for your reflection.
