### ISSUE TITLE
How to automatic display tooltips

### ISSUE THREAD

**Issue by phong764119** [nagix/chartjs-plugin-streaming#23]
Hi, 
I'm working on streaming chartjs and trying to display the tooltip of the newest updating point. How can i do it without using 'mousehover'

**Comment by nagix** [comment]
As chartjs-plugin-streaming keeps a mouse event object in `chart.lastMouseMoveEvent` and dispatches it on every frame update, you can use it.

See an example at https://jsfiddle.net/nagix/y70hneg7/.

**Comment by nagix** [comment]
`chart.lastMouseMoveEvent` was replaced with `chart.streaming.lastMouseEvent` in v1.6.0. The example above was updated accordingly.
