### ISSUE TITLE
Realtime chart makes 'time' charts become realtime charts

### ISSUE THREAD

**Issue by schlunsen** [nagix/chartjs-plugin-streaming#24]
Hi,

I'm having some issues placing both a chart of x-axis type 'time' along with a realtime chart.

It seems like the 'time' chart is being overruled by the realtime x-axis even if the x-axis is set to 'time', making both charts realtime charts.

Is there something that I may be missing?

Thanks again for a great chartjs plugin!

**Comment by nagix** [comment]
When a chart has a 'time' scale and the charts-plugin-streaming is loaded, the scale is automatically interpreted as a 'realtime' scale for a historical reason. You can set `options.plugins.streaming` to `false` to use a 'time' scale in a chart.

See https://jsfiddle.net/nagix/eh4hsnu6/.

**Comment by schlunsen** [comment]
Thanks for the quick answer!
