### ISSUE TITLE
Support for different time zones

### ISSUE THREAD

**Issue by schlunsen** [nagix/chartjs-plugin-streaming#25]
It could be nice if you were able to set a different time zone then one the client is currently in.

Any hints on how to make this possible?

**Comment by nagix** [comment]
If you just want to display time in a different time zone on an axis, you can use custom display formats to output a unix timestamp, convert it into a moment object, add a time offset and format it as follows.
```
scales: {
  xAxes: [{
    type: 'realtime',
    time: {
      displayFormats: {
        second: 'x',
        minute: 'x'
      }
    },
    ticks: {
      callback: function(v) {
        return moment(Number(v)).zone('+01:00').format('h:mm:ss a');
      }
    }
  }]
}
```
See an example at https://jsfiddle.net/nagix/ffcbsng2/.

**Comment by nagix** [comment]
Closing as answered.
