### ISSUE TITLE
Pie charts are broken on page including chartjs-plugin-streaming

### ISSUE THREAD

**Issue by ubugnu** [nagix/chartjs-plugin-streaming#26]
When a pie chart is present on a page including chartjs-plugin-streaming, I got the following errors:

```
Uncaught TypeError: Cannot read property 'xAxes' of undefined
chartjs-plugin-streaming.min.self-Uncaught TypeError: Cannot read property 'getScaleForId' of null
```

**Comment by ubugnu** [comment]
A quick workaroud is to disable straming plugin on charts that do not support/use it:

```
var chart = new Chart(ctx, {
    config: {
        plugins: {
            streaming: false
        }
    }
});
```

**Comment by nagix** [comment]
Thank you for reporting this issue and the workaround. The error occurs because a pie (doughnut, polar area and radar) chart doesn't have the `scales` option in the config and the plugin doesn't check it. I will fix it shortly.

**Comment by jackkav** [comment]
I think the plugin should only be loaded when the xAxes contains a type of `realtime`. Otherwise is will disrupt other charts on the same page.
