### ISSUE TITLE
Multi-Datasets Chart streaming with pause

### ISSUE THREAD

**Issue by williamesp2015** [nagix/chartjs-plugin-streaming#27]
You provided a great facility for data streaming but the examples are having the same format. Could you please add an multi datasets (time,A1,A2,A3,A4) chart with pause key in the chartjs-plugin-streaming repository. Thank you

**Comment by nagix** [comment]
I have added the pause feature in 5e5a7ee. For a dataset format, this plugin doesn't intend to support any new specific format. A similar request was recently raised in chartjs/Chart.js#5403, but the recommended way is to convert your data into the Chart.js ones.
