### ISSUE TITLE
Cordova Projects

### ISSUE THREAD

**Issue by BrunoGiubilei** [nagix/chartjs-plugin-streaming#28]
this plugin dont works with cordova based projects.

Screenshot for PC
![localhost_8001_main html iphone 5_se](https://user-images.githubusercontent.com/2066556/40628277-6b67b4d2-629a-11e8-89e4-1a54b80839f3.png)

Screenshot for Mobile
![0a9132e8-5782-46dd-8d1c-982c855f84b7](https://user-images.githubusercontent.com/2066556/40628306-913464b2-629a-11e8-8879-19043b2f3c64.jpg)

**Comment by nagix** [comment]
Thank you for reporting this issue. Is this chart shown correctly using the 'time' scale in Chart.js without this plugin? I want to confirm whether the problem is in Chart.js or this plugin.

**Comment by BrunoGiubilei** [comment]
never mind, I got confused, I made the function call too soon, its plugin works great with projects Cordova
