### ISSUE TITLE
how i create blink bar like this

### ISSUE THREAD

**Issue by pichayean** [nagix/chartjs-plugin-streaming#30]
how i create blink bar like this 
[issue.zip](https://github.com/nagix/chartjs-plugin-streaming/files/2079267/issue.zip)

**Comment by nagix** [comment]
You need to keep the time value for the bar you want to blink, and look up the bar index based on that time value. See the example at https://jsfiddle.net/nagix/gyojxv31.

**Comment by pichayean** [comment]
@nagix 
Thk for this way but
in your example i want chart not slide
Is it possible?

i disabled type: 'realtime', in barOptions  then chart not display 
how i do chart Blink and chart not slide;
please help me


var barOptions = {
  animation : { duration: 0 },
  scales: {
    xAxes: [{
      type: 'realtime',
      ticks: {
        fontSize: 6
      }
    }],
    yAxes: [{
      ticks: {
        fontSize: 7,
        beginAtZero: true,
        max: 10,
        stepSize: 2,
        fixedStepSize: 2
      }
    }]

**Comment by nagix** [comment]
If you don’t want to slide bars, why are you using this plugin? Your example in issue.zip seems to be working well.

**Comment by pichayean** [comment]
@nagix  i think your plugin will be solving my  Problem well more than my way. thank you for your recomendation.
