### ISSUE TITLE
[Angular]How do I control the refresh timing with input binding other than with the numeric value

### ISSUE THREAD

**Issue by binDongKim** [nagix/chartjs-plugin-streaming#31]
```javascript
@Input() a

...

this.chartObj = new Chart(this.el.nativeElement.getContext('2d'), {
	...
	options: {
		plugins: {
			streaming: {
				refresh: 1000, // onRefresh callback will be called every 1s
				onRefresh: (chart: Chart) => {
					// something
				}
			}
		}
	}
});
```
With the above snippet, I'd like to control the refresh the chart when I get the new input data `a` but apparently, the datasets only get updated every 1s.

I've tried using `ngOnChanges` cycle, pushing the new data to the datasets and update the chart instance but it didn't seem to work.
```javascript
this.chartObj.config.data.datasets.push({
  // label: 'Dataset ' + config.data.datasets.length,
  // backgroundColor: color(newColor).alpha(0.5).rgbString(),
  // borderColor: newColor,
  fill: false,
  lineTension: 0,
  data
});
this.chartObj.update();
```

What am I missing?

**Comment by nagix** [comment]
You need to add new data to `datasets[index].data`, not to `datasets`. Try this code for chart definition:
```javascript
this.chartObj = new Chart(this.el.nativeElement.getContext('2d'), {
  type: 'line',
  data: {
    datasets: [{
      label: 'Dataset 1',
       backgroundColor: color(newColor).alpha(0.5).rgbString(),
       borderColor: newColor,
       fill: false,
       lineTension: 0,
       data: []
    }]
  },
  options: {
    plugins: {
      streaming: {
        duration: 1000
      }
    }
  }
});
```
Then, this for chart update (assuming `yourData` object has `timestamp` and `value` array on every update):
```javascript
this.chartObj.config.data.datasets.forEach(function(dataset, i) {
  dataset.data.push({
    x: yourData.timestamp,
    y: yourData.value[i]
  });
});
this.chartObj.update({
  duration: 0
});
```

**Comment by binDongKim** [comment]
I'm afraid it doesn't work. The data I'm trying to show is number array(e.g. `[1,2,3]`) so I tried like,
```javascript
this.chartObj.config.data.datasets.forEach(function(dataset, i) {
  dataset.data.push({
    y: myData[i]
  });
});
this.chartObj.update({
	duration: 0
});
```
And the `dataset.data.push({y: myData[i]})` gives me typescript compile error, saying calling the wrong signature.

**Comment by nagix** [comment]
You have to set a timestamp (for example, `Date.now()`) to `x` property even if you don't need to show the x-axis labels. To hide the x-axis labels, use the following code:
```javascript
  options: {
    scales: {
      xAxes: [{
        type: 'realtime',
        display: false
      }]
    },
    ...
  }
```

**Comment by binDongKim** [comment]
```javascript
this.chartObj.config.data.datasets.forEach(function(dataset, i) {
    dataset.data.push({
    	x: Date.now(),
        y: data[i]
    });
});
```
I tried like above, and it finally works!
Just one thing. It still gives me the typescript compile error as I mentioned earlier: 

> Calling the wrong signature

Any thought on this?

**Comment by nagix** [comment]
What is the exact typescript compile error message? How do you import Chart.js and chartjs-plugin-streaming?

**Comment by binDongKim** [comment]
The message is: 
> It has no compatible call signature.

And I currently import Chart.js and chartjs-plugin-streaming as:

```javascript
import * as Chart from 'chart.js';
import 'chartjs-plugin-streaming';
```

**Comment by nagix** [comment]
If you are using strict type checking, run `npm install @types/chart.js` and use the following code:
```typescript
import {Chart, ChartDataSets, ChartPoint} from 'chart.js';
import 'chartjs-plugin-streaming';

...

if (this.chartObj.data && this.chartObj.data.datasets) {
  this.chartObj.data.datasets.forEach(function(dataset: ChartDataSets, i: number) {
    (dataset.data as ChartPoint[]).push({
      x: Date.now(),
      y: data[i]
    });
  });
}
this.chartObj.update({
  duration: 0
});
```
