### ISSUE TITLE
How to trigger the pause?

### ISSUE THREAD

**Issue by binDongKim** [nagix/chartjs-plugin-streaming#32]
I'd like to pause the chart on certain input bindings. How do I trigger the pause?

**Comment by nagix** [comment]
Version 1.5 introduced the pause feature. Set `chart.options.plugins.streaming.pause` to a Boolean value to pause/resume scrolling. See also [an example](https://nagix.github.io/chartjs-plugin-streaming/samples/interactions.html)
```javascript
chart.options.plugins.streaming.pause = true;
chart.update({
  duration: 0
});
```
