### ISSUE TITLE
How to set the max y according to the realtime data?

### ISSUE THREAD

**Issue by binDongKim** [nagix/chartjs-plugin-streaming#33]
I'd like to reset the max ticks of yAxes dynamically when based on the realtime data. I tried implementing it as following: 
```javascript
// Angular 5+
// When the new data arrives,
// data: number[]
this.chartObj.config.options.scales.yAxes[0].ticks.max = Math.max(...data) >= 5 ? undefined : 5; // 5: default Y max value
```

But if the new data's max value is 3, for example, the max Y sets as 5 and if the previous max value is 8 and the data is still drawn on the chart, the result is not right. So my question is, how can I figure out the max data on the chart area so that I could set the max Y accordingly?

Many thanks!

**Comment by nagix** [comment]
If your data is in `{x: <timestamp>, y: <value>}` format, you can get the maximum value as follows: 
```typescript
this.chartObj.config.options.scales.yAxes[0].ticks.max =
  Math.max(...this.chartObj.data.datasets.map(function(dataset: ChartDataSets) {
    return Math.max(...(dataset.data as ChartPoint[]).map(function(value) {
      return value.y as number;
    }));
  })) >= 5 ? undefined : 5;
```

**Comment by binDongKim** [comment]
Many thanks!
