### ISSUE TITLE
Smooth scale changes

### ISSUE THREAD

**Issue by j0hnm4r5** [nagix/chartjs-plugin-streaming#38]
When Chart.js rescales to fit the data in the chart within the y-axes, it does so rather abruptly (as seen [here](https://i.imgur.com/Y5NWyWK.gifv)). Ideally, the transition should be smooth, similar to [Smoothie Charts](http://smoothiecharts.org/tutorial.html).

**Comment by nagix** [comment]
This plugin disables an animation of data addition at `onRefresh` for the performance reason. If you want smooth transition, add `chart.update()` at the end of `onRefresh` function like this:
```javascript
plugins: {
  streaming: {
    onRefresh: function(chart) {
      chart.data.datasets.forEach(function(dataset) {
        dataset.data.push({
          x: Date.now(),
          y: Math.random()*100
        });
      });
      chart.update();
    }
  }
}
```

**Comment by j0hnm4r5** [comment]
Awesome! That worked great. Thank you!
