### ISSUE TITLE
Start right away with a delay

### ISSUE THREAD

**Issue by GijsGoudzwaard** [nagix/chartjs-plugin-streaming#39]
In my case I have a slow stream that updates every 5 seconds which i've specified with the `delay` property. The problem with this is that the data will be fetched after 5 seconds so my users have to wait 5 seconds before they can read the chart. The data is available right away, so is there an option that I can start immediately instead of waiting 5 seconds or preloading that data somehow?

**Comment by nagix** [comment]
You can preload the data in the same way as a normal chart like the example below. You can also update `chart.data.datasets` anytime (`chart.update()` needs to be called in that case). 
```
var yourDatasets = preloadDatasets();

var ctx = document.getElementById('myChart').getContext('2d');
var chart = new Chart(ctx, {
  type: 'line',
  data: {
    datasets: yourDatasets
  },
  options: {
    scales: {
      xAxes: [{
        type: 'realtime'
      }]
    },
    plugins: {
      streaming: {
        onRefresh: yourRefreshFunction()
      }
    }
  }
});
```

**Comment by GijsGoudzwaard** [comment]
Thanks that worked
