### ISSUE TITLE
Stream Past Data

### ISSUE THREAD

**Issue by CraigLee17** [nagix/chartjs-plugin-streaming#41]
Hi, I want to know if there is a way to stream past data. Here are the details:

- I receive a past data array which is gathered in the backend from date1 to date1. (Both date1 and date2 are past dates)

- I want to stream the data array from the beginning to the end.

Thanks a lot!

**Comment by nagix** [comment]
You can delay the start of streaming using `delay` property. In this case, set `delay` to `Date.now() - date1.getTime()` (assuming `date1` is a `Date` object) and stream the data with the past timestamps. You can preload all the data to `chart.data.datasets` at a time, but it might be better to use `onRefresh()` to feed the data periodically if the data size is big.

**Comment by CraigLee17** [comment]
Sounds good. Thank you!

**Comment by CraigLee17** [comment]
Inside onRefresh(), I cannot get the service from my component. Any idea about it?

```
this.mychart.chart.options.plugins.streaming.onRefresh = (chart: any) => {
      chart.data.datasets.forEach(function (dataset: any) {
        this.myService.getDataById(this.id).subscribe(data => {
            dataset.data.push(data);
        });
     });
};
```

**Comment by nagix** [comment]
`this` value In the `onRefresh` function is not the same as the `this` value for the function that set `onRefresh` because it is called by the callback function of `setInterval`. [Here]( https://stackoverflow.com/questions/20279484/how-to-access-the-correct-this-inside-a-callback) is the solution.

**Comment by CraigLee17** [comment]
Thanks a lot!
