### ISSUE TITLE
Spacing between X-axis ticks

### ISSUE THREAD

**Issue by kurtzky** [nagix/chartjs-plugin-streaming#48]
My chart data refreshes every 3 seconds. I've set the X-axis stepSize to 20 so I have a 20-second interval between ticks. But the resulting chart shows big gaps between these ticks. Is there a way to "squeeze" them so the intervals are close to each other?

JSFiddle: [https://jsfiddle.net/xbqthaoL/5/](https://jsfiddle.net/xbqthaoL/5/)

**Comment by nagix** [comment]
Please set the `duration` option to a larger value, 500000 for example.

**Comment by nagix** [comment]
Closing as answered.
