### ISSUE TITLE
Streaming from left to right

### ISSUE THREAD

**Issue by mynote** [nagix/chartjs-plugin-streaming#51]
Couldnt find any options to stream the charts from left to right instead of right to left. Is there any way to realize that without doing code changes to the plugin?

**Comment by nagix** [comment]
Chart.js doesn't support a reversed time scale yet, but some work is in progress in chartjs/Chart.js#3279. Once it is done, I will work on this.

**Comment by nagix** [comment]
As the reversed time scale is added in chartjs/Chart.js#5927, the reversed realtime scale is supported in f320883. This feature is expected to be available in Chart.js 2.8 with chartjs-plugin-streaming 1.8.

**Comment by nagix** [comment]
Version 1.8.0 was just released.
