### ISSUE TITLE
Chartjs plugin streaming in angular7 doesnt work

### ISSUE THREAD

**Issue by DianPermana** [nagix/chartjs-plugin-streaming#55]
Hello sir,  I am dian from indonesia,  i have tried for chart.js plugin streaming in angular 7, but when I run this plugin (https://nagix.github.io/chartjs-plugin-streaming/ ) doesnt work (not display graph).  And then,  I have tried chart.js in angulat 7 from "https://valor-software.com/ng2-charts/" it's work.  where is the problem,  i dont understand.  Please can you review this problem.

**Comment by adripanico** [comment]
I've used it with Angular 6 and I've recently updated to Angular 7 without any issue.

**Comment by johndacost** [comment]
Hi, almost the same problem... I follow this [sample](https://nagix.github.io/chartjs-plugin-streaming/) and
I can see the graph wihout data but when I add some data I got this `ERROR TypeError: Cannot read property 'getPixelForValue' of undefined`

**Comment by nagix** [comment]
@johndacost Do you see any error messages in console?

**Comment by adripanico** [comment]
> Hi, almost the same problem... I follow this [sample](https://nagix.github.io/chartjs-plugin-streaming/).
> 
> but onRefresh: function (chart) {...} is never call
> 
> ```
>   public options: any = {
>     scales: {
>       xAxes: [{
>         type: 'time',
>         realtime: {
>           duration: 20000,    // data in the past 20000 ms will be displayed
>           refresh: 1000,      // onRefresh callback will be called every 1000 ms
>           delay: 1000,        // delay of 1000 ms, so upcoming values are known before plotting a line
>           pause: false,       // chart is not paused
>           ttl: undefined,
>           // a callback to update datasets
>           onRefresh: function (chart: any) {
>             debugger;
>             // query your data source and get the array of {x: timestamp, y: value} objects
>             var data = [Math.random()];
>             // append the new data array to the existing chart data
>             Array.prototype.push.apply(chart.data.datasets[0].data, data);
>           }
>         }
>       }]
>     },
>     plugins: {
>       streaming: {            // per-chart option
>         frameRate: 30       // chart is drawn 30 times every second
>       }
>     }
> ```

I am not using it this way. I have no ```realtime``` property. Try this:
```
public options: any = {
  scales: {
    xAxes: [{
      type: 'realtime',
    }]
  },
  plugins: {
    streaming: {
      frameRate: 30,
      duration: 20000,
      refresh: 1000,
      delay: 1000,
      onRefresh: (chart: any) => {
        ...
      }
    }
  }
}
```

**Comment by johndacost** [comment]
> @johndacost Do you see any error messages in console?

Nope... no error catched..
**Congifuration**

- Angular6
- ionic4

**live.page.module.ts**
```
@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    IonicModule,
    ChartsModule,
    RouterModule.forChild(routes)
  ],
  declarations: [LivePage]
})
```
export class LivePageModule { }

**live.page.html**
```
    <div style="display: block">
      <canvas baseChart [chartType]="'line'" [datasets]="datasets" [options]="options">
      </canvas>
    </div>
```

**live.page.ts**

```
  ...
  import 'chartjs-plugin-streaming';
  ...
  datasets: any[] = [{ data: [] }, { data: [] }];
  options: any = {
    scales: {
      xAxes: [{ type: 'realtime' }]
    },
    plugins: {
      streaming: {
        frameRate: 30,
        duration: 20000,
        refresh: 1000,
        delay: 1000,
        onRefresh: function (chart: any) {
          console.log("test");
          chart.data.datasets.forEach(function (dataset: any) {
            dataset.data.push({
              x: Date.now(),
              y: Math.random()
            });
          });
        },
      }
    }
  };
```

**Result**
![image](https://user-images.githubusercontent.com/3956368/52406025-03af6780-2acd-11e9-9d5d-d573dd4c5e28.png)

**Comment by johndacost** [comment]
> > Hi, almost the same problem... I follow this [sample](https://nagix.github.io/chartjs-plugin-streaming/).
> > but onRefresh: function (chart) {...} is never call
> > ```
> >   public options: any = {
> >     scales: {
> >       xAxes: [{
> >         type: 'time',
> >         realtime: {
> >           duration: 20000,    // data in the past 20000 ms will be displayed
> >           refresh: 1000,      // onRefresh callback will be called every 1000 ms
> >           delay: 1000,        // delay of 1000 ms, so upcoming values are known before plotting a line
> >           pause: false,       // chart is not paused
> >           ttl: undefined,
> >           // a callback to update datasets
> >           onRefresh: function (chart: any) {
> >             debugger;
> >             // query your data source and get the array of {x: timestamp, y: value} objects
> >             var data = [Math.random()];
> >             // append the new data array to the existing chart data
> >             Array.prototype.push.apply(chart.data.datasets[0].data, data);
> >           }
> >         }
> >       }]
> >     },
> >     plugins: {
> >       streaming: {            // per-chart option
> >         frameRate: 30       // chart is drawn 30 times every second
> >       }
> >     }
> > ```
> 
> I am not using it this way. I have no `realtime` property. Try this:
> 
> ```
> public options: any = {
>   scales: {
>     xAxes: [{
>       type: 'realtime',
>     }]
>   },
>   plugins: {
>     streaming: {
>       frameRate: 30,
>       duration: 20000,
>       refresh: 1000,
>       delay: 1000,
>       onRefresh: (chart: any) => {
>         ...
>       }
>     }
>   }
> }
> ```

I try your solution but still not refresh the graph :(

**Comment by adripanico** [comment]
But is it calling to onRefresh method?

**Comment by johndacost** [comment]
> But is it calling to onRefresh method?

nope. I put a console.log("call") in the onRefresh method and nothing appear

**Comment by johndacost** [comment]
> @johndacost Do you see any error messages in console?

In fact, yes when i try to add data with a click function I got this` LivePage.html:47 ERROR TypeError: Cannot read property 'getPixelForValue' of undefined`

**Comment by nagix** [comment]
Closing as a solution was suggested.
