### ISSUE TITLE
Update chart data by Axis ID

### ISSUE THREAD

**Issue by kurtzky** [nagix/chartjs-plugin-streaming#56]
I have one x-axis and two y-axis data. I declare my datasets as follows:

`chart.data.datasets.push({
    yAxisID: "ID1",
    label: "Label1"
});`

`chart.data.datasets.push({
    yAxisID: "ID2",
    label: "Label2"
});`

How do I update my dataset by ID and not by index? Something like `chart.data.datasets[yAxisID = "Label1"].data.push({});.`

So far I can append data by index similar to below:

`chart.data.datasets[0].data.push({
    x: 4,
    y: 6.5
});`

My intention is to continuously update the chart over a period of time. My data values come from a data source that feeds me data continuosly. This service only gives me the ID and the corresponding value. Every time I get data from the service, I want to push it to the chart.

**Comment by nagix** [comment]
There is no public method that accept scale ID directly, so you can write code like
```js
chart.data.datasets.forEach(function(dataset) {
    if (dataset.id === id) {
        dataset.data.push({/* ... */});
    }
});
```
or use a dictionary to map an ID to the index.
```js
var mapping = {'ID1': 0, 'ID2': 1};
/* ... */
chart.data.datasets[mapping[id]].data.push({/* ... */});
```

**Comment by nagix** [comment]
Closing as the solution was provided.
