### ISSUE TITLE
Time range question

### ISSUE THREAD

**Issue by monstasat** [nagix/chartjs-plugin-streaming#57]
I've been used your plugin to display data coming from a remote device. The data is retrieved via WebSocket and is timestamped by the device. 

Everything worked fine until I realized that time settings can be different on a client PC and a remote device. For example, if the time on the client PC is 5 minutes behind than the time on the remote device, the data will be shown on the chart only after five minutes. This is what is expected because the data should be shown as soon as it arrives, but with those timestamps that are sent by the remote device.

Does your plugin always set time scale range according to the client PC time settings? Can the range be overridden according to the incoming data? Is this plugin suitable for my purpose or your approach described [here](https://github.com/nagix/chartjs-plugin-streaming/issues/52#issuecomment-437426542) is more appropriate in my case?

I like how the plugin works, the data is shown very smoothly. I'd like to keep this behavior in my app, but don't sure if this is possible due to different time settings in the remote device and client PC.

**Comment by nagix** [comment]
You can use the `delay` option to adjust the time range you want to show. For example, if the time on your client PC is 5 minutes behind, you can set `delay` to `-30000` to show the stream in realtime. If it is 5 minutes ahead, you can set `delay` to `30000`.

**Comment by nagix** [comment]
Closing as the question was answered.
