### ISSUE TITLE
Draw a line over the chart

### ISSUE THREAD

**Issue by cohenu** [nagix/chartjs-plugin-streaming#58]
Hey all,
I have a small question, Can I draw a permanent line over the chart ? 
this is my script without the streaming plugin, can I do something like that ?
`data: Array.apply(null, new Array(data.games)).map(Number.prototype.valueOf, myAvg),
label: 'My Avg',
fill: false,
radius: 0,
borderWidth: 1,
borderColor: '#3E311C',
pointHoverRadius: 0`

Thanks in advanced!

**Comment by nagix** [comment]
I think [chartjs-plugin-annotation](https://github.com/chartjs/chartjs-plugin-annotation) can be used to draw the avarage line. See also the [example](https://nagix.github.io/chartjs-plugin-streaming/samples/annotation.html).

**Comment by cohenu** [comment]
Thank you! Thank you! Thank you! running to check it out :-)

**Comment by cohenu** [comment]
It's working thank you!!!
Do you know about a plugin that can put icon on the chart? (I'm trying to create a event timeline each event have different icon)
