### ISSUE TITLE
Feature-req: Perf options

### ISSUE THREAD

**Issue by cythrauL** [nagix/chartjs-plugin-streaming#6]
The graphs produced by this plugin are very beautiful, but they use a lot of cpu, are there any, or could there be any configurable perf options; perhaps make the animation less fluid at the cost of cpu cycles?

**Comment by nagix** [comment]
I think it is great idea to introduce something like the frame-per-second rendering option. I will work on it when I have time.

**Comment by nagix** [comment]
I have added the `frameRate` option and set the default value to `30` with f1e773e to lower CPU usage. See this sample: https://jsfiddle.net/nagix/wgswzor3/. I also recommend to disable animation as stated at [Chart.js docs](http://www.chartjs.org/docs/latest/charts/line.html#disable-animations).
