### ISSUE TITLE
Create padding from the right side

### ISSUE THREAD

**Issue by cohenu** [nagix/chartjs-plugin-streaming#60]
Hey @nagix,
I know that I can use the following:
```js
        layout: {
            padding: {
                left: 0,
                right: 30,
                top: 0,
                bottom: 0
            }
        },
```
to create padding from the right side, when I do that and draw an average line the average line gets also the padding. Is there a way to draw the line on 100% of the canvas and the new values will start from 30px from the right? 

Edit:
Another option is to start the streaming 30px from the right - but keep the chart size as before, is it possible ?

I found that chart.annotation.elements.myAvg.chartInstance.boxes[0].margins.right set to 30 can I override it and set this to 0 ?

**Comment by nagix** [comment]
chartjs-plugin-annotation doesn't support it, but you can write your own plugin code to draw the average line. For example:
```js
new Chart(ctx, {
    // ...
    plugins: [{
        afterDraw: function(chart) {
            var ctx = chart.ctx;
            var y = chart.scales['y-axis-0'].getPixelForValue(avg);

            ctx.lineWidth = 3;
            ctx.strokeStyle = '#ff0000';
            ctx.beginPath();
            ctx.moveTo(0, y);
            ctx.lineTo(chart.width, y);
            ctx.stroke();
        }
    }]
}
```
See https://www.chartjs.org/docs/latest/developers/plugins.html for more details.

**Comment by cohenu** [comment]
I managed to draw the line with 100% width by creating another chart over the first chart (with the padding) and fetch the data from the same source and in each push check y-axis values and fix them if needed, not the easy way but it's working :) 
thank you again for your help!
