### ISSUE TITLE
The plugin doesn't work on phone

### ISSUE THREAD

**Issue by giocap99** [nagix/chartjs-plugin-streaming#63]
Hi, i'm using your plugin and it works fine on pc. On phone it doesn't show the graph scrolling, neither it shows the lines of the graph. I'm using Google Chrome on Android 8.0. I tried it on another browser but still the same result.

**Comment by nagix** [comment]
I tested the samples with multiple Android 8.0 devices but all worked well. Can you shere your code using jsfiddle or codepen?

**Comment by giocap99** [comment]
I have a lot of data that needs to be rendered in the graph, maybe it's this the problem?

https://jsfiddle.net/jgrve0aq/

**Comment by nagix** [comment]
Is this working code? `dataPoints1` is used here, so it should be an array of `{x, y}` objects or an empty array. 
```js
var myChart = new Chart(ctx, {
    type: 'line',
    data: {
        datasets: [{
            data: dataPoints1,
```
But, this `dataPoints1` must be a number here as Y axis is a linear scale.
```js
onRefresh: function(chart) {
    myChart.data.datasets.forEach(function(dataset) {
        dataset.data.push({
            x: Date.now(),
            y: dataPoints1
        });
    });
}
```

**Comment by giocap99** [comment]
The var dataPoints1 is an array:

` var dataPoints1	= []; 
dataPoints1.push({
          x: parseInt(elements[0]*1000),
          y: parseFloat(elements[1])
        });`

**Comment by nagix** [comment]
Is `dataPoints1[*].x` a unix timestamp? As `x` must be a value [Moment.js](https://momentjs.com/docs/#/parsing/) can parse and `y` must be a number, you can write `onRefresh` as follows (you cannot set `y` to an array). 
```js
onRefresh: function(chart) {
    myChart.data.datasets.forEach(function(dataset) {
        // ...
        dataset.data.push({
            x: timestamp, // time in millisecond since the unix epoch
            y: value      // a number
        });
    });
}
```

**Comment by giocap99** [comment]
Hi, i donwloaded the latest version (min version) of the plugin and it works fine. Thank you.
