### ISSUE TITLE
financial chart.js candlestick tooltip not displaying

### ISSUE THREAD

**Issue by rashearth** [nagix/chartjs-plugin-streaming#65]
Hi, Nagix-san

Thank you so much for the wonderful application ;)
I really love using your financial candlestick chart.

Today, i have one question for the title.
As i have been working out, I found out that the tooltip doesn't display, even in your sample data financial.html.
I changed the {tooltip  enabled: true,}, but still, doesn't work out.
Please tell me if there is any way to display the tooltip.

Thank you

**Comment by nagix** [comment]
Thanks for reporting this issue. I found that this is a bug in chartjs-chart-financial and opened a PR (chartjs/chartjs-chart-financial#48).

For the meantime, you can use the following workaround. Without the fix, the tooltip will not be centered on the candle and frequently move, though.
```js
tooltips: {
    position: 'nearest'
}
```

**Comment by nagix** [comment]
The bug in chartjs-chart-financial was fixed. You can build `Chart.Financial.js` using its master branch and it should work with chartjs-plugin-streaming without `options.tooltips` configuration.

**Comment by nagix** [comment]
I have updated the [financial chart sample](https://nagix.github.io/chartjs-plugin-streaming/samples/financial.html) enabling the tooltip.

**Comment by rashearth** [comment]
Thank you for your help!
It all worked fine : )
