### ISSUE TITLE
How to add custom tooltip

### ISSUE THREAD

**Issue by sandeepmeenuga** [nagix/chartjs-plugin-streaming#67]
It's choosing default tooltip, is there any way to add my own tooltip.

**Comment by nagix** [comment]
You can use custom tooltips as described in the [Chart.js document](https://www.chartjs.org/docs/latest/configuration/tooltip.html#external-custom-tooltips).

**Comment by sandeepmeenuga** [comment]
Thank you, I went through and resolved.
