### ISSUE TITLE
mixed chart for vertical and horizontal barchart

### ISSUE THREAD

**Issue by rashearth** [nagix/chartjs-plugin-streaming#68]
Hi, thanks again for this wonderful application.
I am wondering if this streaming application could be implemented with mixed chart with horizontal and vertical bar chart as below.
<img width="330" alt="スクリーンショット 2019-03-10 10 42 18" src="https://user-images.githubusercontent.com/26535295/54079520-4f01a380-4321-11e9-96a8-3378125ea7f5.png">
(maybe a bit similar case with this issue
https://github.com/chartjs/Chart.js/issues/4096
)

I am trying to implement by using 2 X axisID's, but the horizontal chart would not show up.
is this function could not be implemented? 
Please kindly confirm

thank you and regards,

**Comment by nagix** [comment]
What is the purpose of using horizontal bars in your use case? If it is for annotation, you may be able to use chartjs-plugin-annotation ([example](https://nagix.github.io/chartjs-plugin-streaming/samples/annotation.html)). If it is for showing a histogram on y axis, Chart.js doesn't have a capability to mix vertical and horizontal bars in a chart.

**Comment by rashearth** [comment]
Thanks, i understand.
How about including financial charts with horizontal bar chart?
To say the truth, i wanted to make chart like the below one, to understand how many orders there are for each of the stock price.

https://goo.gl/images/4be95J

The bar shows the unimplemented orders, the financial shows the stock or other prices.

**Comment by nagix** [comment]
Chart.js doesn't have such a future, but one option would be overlaying a candlestick realtime chart and a horizontal bar chart like this example: https://jsfiddle.net/nagix/5un6fjpk/. It might be a bit challenging to synchronize x & y scales between two charts, though.

**Comment by rashearth** [comment]
Thanks for your support.
I understood.
I thought that i could work this out by synchronizing two charts.
is there any way to confirm or "return" the max & min of the main chart?
if so, i could synchronize main chart(candlestick) and sub chart(with horizontal barchart) .

**Comment by nagix** [comment]
You can get the min and max values in the main chart in its `onRefresh` function as follows. Then, these values can be used to update the horizontal bar chart.

```js
var min = Math.min(...chart.data.datasets[0].data.map(function(value) {
    return value.l;
}));
var max = Math.max(...chart.data.datasets[0].data.map(function(value) {
    return value.h;
}));
```

**Comment by rashearth** [comment]
Thx! i think i could handle this!
