### ISSUE TITLE
plugin is broken with chart.js 2.8

### ISSUE THREAD

**Issue by aljones15** [nagix/chartjs-plugin-streaming#69]
Issue is an adapter is missing.

TypeError: Cannot read property 'date' of undefined

		var adapter = me._adapter = new core_adapters._date(options.adapters.date);

with chart.js 2.7.3 it works fine. anyways you are probably aware of the issue.

btw I loaded your plugin using inline i.e.

```js
plugins: [streaming]
```
Sorry about so little info.

**Comment by nagix** [comment]
Thanks for reporting this. I’m planning to release a new version that supports Chart.js 2.8 in a few days.

**Comment by nagix** [comment]
Version 1.8.0 was just released.
