### ISSUE TITLE
No x axis ticks or labels

### ISSUE THREAD

**Issue by ericsvendsen** [nagix/chartjs-plugin-streaming#7]
I'm unable to get x axis ticks or labels to render like they do in the tutorial. I copied and pasted from the source of your tutorial and created a [jsfiddle](https://jsfiddle.net/bvc51gcc/) to demonstrate the issue.

**Comment by farshidpg** [comment]
i have too ! i copy all of sample code . and x axis ticks  not show ! and  i dont have error

x axis ex : 9:58:22 ( hh:mm:ss ) :/

**Comment by farshidpg** [comment]
i found way !!

 if use Cart.js version 2.7.1  x axis ticks not show !

should use Chart.js  version 2.6.1  to  work successfuly ...
wts problem  with 2.7.1 ?

**Comment by nagix** [comment]
v1.2.0 supported Chart.js 2.6 only. Today we released v1.3.0 which supports Chart.js 2.7 and you will see that the issue is fixed.
