### ISSUE TITLE
How to support dayjs as alternative to moment?

### ISSUE THREAD

**Issue by danyalejandro** [nagix/chartjs-plugin-streaming#74]
I use Dayjs instead of Moment because including the later will make any script remarkably heavier: In many cases Moment is heavier than your javascript bundle as a whole, even after getting rid of locale. This is a problem for certain applications (i.e. my users work in the ocean & the arctic).

Dayjs was built to have the same syntax as moment, so a quick search & replace in your script makes it work instantly. How can I add dayjs support to this project?

**Comment by danyalejandro** [comment]
After trying this out (and creating an adapter) I noticed this plugin doesn't allow the use of adapters

**Comment by nagix** [comment]
The version 1.x of this plugin requires Moment.js as a peer dependency for backward compatibility with Chart.js 2.7. As you mentioned, however, you can use other date libraries with corresponding adaptors and Chart.js 2.8 or later.
