### ISSUE TITLE
AngularJS and Firebase

### ISSUE THREAD

**Issue by paolo0926** [nagix/chartjs-plugin-streaming#77]
Hi, I can't fetch data from my firebase realtime database to my realtime chart. I'm using AngularJS in programming but I don't really know how to fetch the data and push it to the realtime chart. I've searched and tried most of the posts online but all I could do is have the data printed on the console.log. Please help.

**Comment by paolo0926** [comment]
This is my code on the component.ts=================

import {Component, OnInit} from '@angular/core';
import 'chartjs-plugin-streaming';
import { Chart } from 'chart.js';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})

export class HomeComponent implements OnInit{
  public canvas;
  public ctx;
  constructor(){}

  ngOnInit(){
    this.canvas=document.getElementById('myChart');
    this.ctx=this.canvas.getContext('2d');
    
    let myChart = new Chart(this.ctx, {
      type:'line',
      data: {
        datasets: [{
          label: 'Node 1',
          data: []
        },{
          label: 'Node 2',
          data: []
        }];
      },
      options: any = {
        scales: {
          xAxes: [{
            type: 'realtime'
          }]
        }
      };
    })
    
    let admin = require('firebase-admin');
    let db = admin.database();
    let ref = db.ref("measurement/node1");
    ref.on("child_changed", function(snapshot) {
      var changedData = snapshot.val();
      myChart.data.datasets[0].data.push({
        x: Date.now(),
        Y: changedData.val()
      });
      myChart.update({
        preservation: true
      });
    })
  }
}

This one is for the component.html============

<div>
  <div style="display: block;">
    <canvas id="myChart">
    </canvas>
  </div>
</div>

**Comment by paolo0926** [comment]
This one is for the component.html============


<div>
  <div style="display: block;">
    <canvas id="myChart">
    </canvas>
  </div>
</div>

**Comment by nagix** [comment]
There are syntax errors on the chart creation.

```typescript
    let myChart = new Chart(this.ctx, {
      type:'line',
      data: {
        datasets: [{
          label: 'Node 1',
          data: []
        },{
          label: 'Node 2',
          data: []
        }]
      },
      options: {
        scales: {
          xAxes: [{
            type: 'realtime'
          }]
        }
      }
    });
```

**Comment by paolo0926** [comment]
Hi, I tried to modify the code with this but there are multiple errors on the terminal on compilation and I'm not quite sure why.
![errors](https://user-images.githubusercontent.com/40094551/58429183-9ce3a780-80d7-11e9-898d-d87961e09e7a.png)
.
this is the code:


`import {Component, OnInit} from '@angular/core';
import 'chartjs-plugin-streaming';
import { Chart } from 'chart.js';


@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})

export class HomeComponent implements OnInit{
  public canvas;
  public ctx;
  constructor(){}

  ngOnInit(){
    this.canvas=document.getElementById('myChart');
    this.ctx = this.canvas.getContext('2d');

    let myChart = new Chart(this.ctx, {
      type: 'line',
      data: {
        datasets: [{
          label: 'Node 1',
          data: []
        },{
          label: 'Node 2',
          data: []
        }]
      },
      options: {
        scales: {
          xAxes: [{
            type: 'realtime'
          }]
        }
      }
    });

    let admin = require('firebase-admin');
    let db = admin.database();
    let ref = db.ref("measurement/node1");
    ref.on("child_changed", function(snapshot) {
      var changedData = snapshot.val();
      myChart.data.datasets[0].data.push({
        x: Date.now(),
        Y: changedData.val()
      });
      myChart.update({
        preservation: true
      });
    })
  }
}
`

**Comment by nagix** [comment]
The errors seems to be all about Firebase, not about this plugin. Have you read Step 3 in https://firebase.google.com/docs/web/setup#using-module-bundlers and https://firebase.google.com/docs/database/web/read-and-write?

```bash
$ npm install --save firebase
```

```typescript
import * as firebase from "firebase/app";

let db = firebase.database();
let ref = db.ref("measurement/node1");
ref.on("value", function(snapshot) {
  var changedData = snapshot.val();
  myChart.data.datasets[0].data.push({
    x: Date.now(),
    Y: changedData.val()
  });
  myChart.update({
    preservation: true
  });
});
```

**Comment by nagix** [comment]
In case of Angular, `@angular/fire` package may also be needed.

```bash
$ npm install --save firebase @angular/fire
```

**Comment by nagix** [comment]
Closing as answered.
