### ISSUE TITLE
Doesn't work with Chartjs v2.7.0

### ISSUE THREAD

**Issue by industral** [nagix/chartjs-plugin-streaming#8]

**Comment by lsubi** [comment]
I've tried it with v2.7.1 and it also doesn't work. The dependencies for the plugin is "chart.js": "2.6.0"... so it's not surprising. 

Looking at the changelog from v2.6.0 to v.2.7.0 and there are quite a lot of changes: https://github.com/chartjs/Chart.js/releases

Hoping an update is in the works.

**Comment by nagix** [comment]
v1.2.0 supported Chart.js 2.6 only. Today we released v1.3.0 which supports Chart.js 2.7 and you will see that the issue is fixed.
