### ISSUE TITLE
Angular 7 Cannot read property 'refresh' of undefined

### ISSUE THREAD

**Issue by gornad** [nagix/chartjs-plugin-streaming#80]
Hello,
I just started using this plugin and upon running npm install and importing, I am met with this error:

DashboardComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: Cannot read property 'refresh' of undefined
    at resolveOption (chartjs-plugin-streaming.js:139)
    at startDataRefreshTimer (chartjs-plugin-streaming.js:254)
    at ChartElement.initialize (chartjs-plugin-streaming.js:405)
    at ChartElement.Element (Chart.js:2747)
    at ChartElement [as constructor] (Chart.js:1971)
    at ChartElement [as constructor] (Chart.js:1971)
    at new ChartElement (Chart.js:1971)
    at Chart.js:8620
    at Object.each (Chart.js:1801)
    at Chart.buildOrUpdateScales (Chart.js:8599)

I am clueless as to how to proceed with resolving this. I have the latest versions of moment.js and chart.js. I imported this way into the .ts file where streaming is needed:
import 'chartjs-plugin-streaming';
import * as moment from 'moment';
Any help would be very much appreciated.
Thanks.

**Comment by gornad** [comment]
For some reason, simply importing this plugin into a file where charts of different types were defined (no real-time charts) produced this error. I then changed the type of one of my graphs to realtime without specifying any options then changed the type back to time and now I see no errors.

**Comment by gornad** [comment]
It turns out that the bug occurs when a chart with type 'time' is present without a streaming: false flag.

**Comment by koderi-dp** [comment]
> streaming: false

Hi, where did you set that options, tryed everything but still not working

**Comment by gornad** [comment]
This was a while ago, but in my case, the bug occurred when I had a chart with type time and did not specify if it was streaming or not. So, when you instantiate the chart, in the options property options { }, you add                 
plugins: {
                    streaming: false,
                },

Hope this helps.
