### ISSUE TITLE
Chart xAxis type 'time' triggering 'realtime'?

### ISSUE THREAD

**Issue by SEI-John** [nagix/chartjs-plugin-streaming#85]
Thanks for this library, I've found it really useful so far. 

I am currently using the streaming library elsewhere in my project, however this issue is being raised from using a static graph in a different file:

```javascript
import { Line } from 'react-chartjs-2';
...
<Line
      data={{
        labels: ['Test label'],
        datasets: [{
          label: 'Test data',
          data: [
            {
              x: '2019-03-01',
              y: 10
            },
            {
              x: '2019-04-05',
              y: 16
            },
            {
              x: '2019-05-14',
              y: 50
            },
          ]
        }]
      }}
      options={{
        scales: {
          xAxes: [{
            type: 'time',
            time: { parser: 'YYYY-MM-DD' },
          }]
        }
      }}
    />
...
```

I'm getting the following error:

```
Uncaught TypeError: Cannot read property 'refresh' of undefined
    at resolveOption (chartjs-plugin-streaming.js:128)
    at startDataRefreshTimer (chartjs-plugin-streaming.js:226)
    at ChartElement.initialize (chartjs-plugin-streaming.js:381)
    at ChartElement.Element (Chart.js:2739)
    at ChartElement [as constructor] (Chart.js:1961)
    at ChartElement [as constructor] (Chart.js:1961)
    at new ChartElement (Chart.js:1961)
    at Chart.js:8269
    at Object.each (Chart.js:1784)
    at Chart.buildOrUpdateScales (Chart.js:8245)
    at Chart.initialize (Chart.js:8137)
    at Chart.construct (Chart.js:8116)
    at new Chart (Chart.js:8057)
    at ChartComponent.renderChart (index.js:278)
    at ChartComponent.componentDidMount (index.js:97)
```
Somehow the chartjs-plugin-streaming library is triggering on the xAxis of `type: 'time'`, shouldn't it only trigger on `type: 'realtime'`?

**Comment by ZaLiTHkA** [comment]
not sure if this would make any difference, but have you tried setting your chart's "streaming" plugin options explicitly on the x-axis that needs it? that might possibly help restrict it's "where should I operate" logic check to only that axis on only that chart..

**Comment by ZaLiTHkA** [comment]
@SEI-John, while I was looking through the ChartJS docs now, I just found a nifty little point that I think might be your best option here: plugins can be explicitly [disabled per chart](https://www.chartjs.org/docs/latest/developers/plugins.html#disable-plugins)...

so if you ensure your "static chart" `options` object sets `plugins.streaming = false`, then you should be good to go. :)

**Comment by SEI-John** [comment]
Thanks Andre! I'll try that out later this week.

**Comment by alex2wong** [comment]
It is weird, I came into same error few days ago.. then I look into some of the source code at
https://github.com/nagix/chartjs-plugin-streaming/blob/5a00d3991f740cee546d1cf3676619e501d13e5a/src/scales/scale.realtime.js#L14
```
scaleService.getScaleConstructor = function(type) {
	// For backwards compatibility
	if (type === 'time') {
		type = 'realtime';
	}
	return this.constructors.hasOwnProperty(type) ? this.constructors[type] : undefined;
};
```
I am not sure why type 'time' would get 'realtime' constructor. the code logic later was pretty complex for me.

```
initialize: function() {
		var me = this;

		TimeScale.prototype.initialize.apply(me, arguments);

		// For backwards compatibility
		if (me.options.type === 'time' && !me.chart.options.plugins.streaming) {
			return;
		}

//// **note:** here we did NOT ran into the return, since me.chart.options.plugins.streaming is not empty even though we did not set streaming plugins.

		me.realtime = me.realtime || {};

		startDataRefreshTimer(me);
	},

```
Sure, the simple way to use scale 'time' when you have imported streaming plugin is setting plugins.streaming = false  as @ZaLiTHkA  said.
