### ISSUE TITLE
Question: How to reset my chart if the config parameters change at runtime

### ISSUE THREAD

**Issue by rabac** [nagix/chartjs-plugin-streaming#88]
Hello 
I have the realtime config setup and working fine. 
I want to add functionality that a user could select the refresh interval of the chart. When this happens, I update the config in the chart object, but the chart is not reset. 
So I am updating the duration, refresh and ttl in the following code but still the original duration and refresh rates are being used. 
`
        this.chart.options.scales.xAxes.realtime = {
            duration: 1000 * 60 * 60,
            refresh: 1000 * 10,
            ttl: 1000 * 60 * 60,
            onRefresh: () => this.onRefresh(),
            delay: 100
        }
`
What should I do to get this to work? 
Thank you!

**Comment by nagix** [comment]
Your code has two problems (assuming it uses chartjs-plugin-streaming 1.8 and Chart.js 2.8).

1. `xAxes` option is an array, so it should be `xAxes[0]`
2. The change won't be effective immediately without calling `chart.update()`

So, the following code should work as expected.
```javascript
this.chart.options.scales.xAxes[0].realtime = {
  duration: 1000 * 60 * 60,
  refresh: 1000 * 10,
  ttl: 1000 * 60 * 60,
  onRefresh: () => this.onRefresh(),
  delay: 100
};
this.chart.update({duration: 0})
```
