### ISSUE TITLE
Embedding annotations and re-rendering period

### ISSUE THREAD

**Issue by monstasat** [nagix/chartjs-plugin-streaming#89]
Hi!

I'm working on adding some annotations to my chart with timescale x-axis. In more detail, I want to show some rectangles on my chart indicating lasting states (each rectangle displays a time interval on x-axis).

This works fine, except those rectangles are updated only when the data is added to the chart.
The expected behavior is when the annotations are updated as frequent as the x-axis (according to `frameRate` option).

Here is the codepen illustrating the issue:
https://codepen.io/monstasat/pen/QWLGGWW
Note the annotations are moving abruptly, but I expect them to move as smooth as the x-axis.
How can this be achieved?

**Comment by monstasat** [comment]
I've tried to set the `frameRate` option to be equal to `refresh` period (1 second in my above example), but it led other unexpected behavior. With `frameRate` set to `1`, annotations and scale are updated synchronously. But when I move move cursor over the chart and the tooltip is shown, x-axis is updated more frequently. When I stop moving the cursor, the axis starts moving as expected.
You can observe this issue here: https://codepen.io/monstasat/pen/jONVVjm

**Comment by nagix** [comment]
Closing as the [version 1.9.0](https://github.com/nagix/chartjs-plugin-streaming/releases/tag/v1.9.0) that fixes this issue was just released.
