### ISSUE TITLE
Always Draw points from last data point

### ISSUE THREAD

**Issue by AtifJaved1** [nagix/chartjs-plugin-streaming#9]
Let's say the I refresh values after every 5 minutes. But sometimes there will be no value. The last point is just pass and not showing on the graph. Say after 20 minutes I have a new value to be added. The issue is not that the new values are linked to the last shown values that were 20 minutes ago. Though it doesn't have to link to that point whose time is passed.
<img width="998" alt="screen shot 2018-02-04 at 2 33 37 am" src="https://user-images.githubusercontent.com/26598012/35771767-dae96c1a-0953-11e8-9950-8a16013fdf0c.png">

**Comment by nagix** [comment]
The current version automatically deletes old data as it disappears off the chart. Do you think it is helpful to have the option that disables automatic deletion of old data to solve this issue?

**Comment by nagix** [comment]
v1.6.0 added the new `ttl` option that removes data points after the time specified. This will prevent a line from being drawn to the old data.
