### ISSUE TITLE
Pause not implemented properly

### ISSUE THREAD

**Issue by RatherLogical** [nagix/chartjs-plugin-streaming#91]
The pause feature does indeed pause the scroll of data across the screen. But if I stop my data source and pause the chart, when it is resumed it jumps back to the last data.

Is there any way to make the chart completely stop scrolling like a real pause and resume?

**Comment by nagix** [comment]
You can easily implement it as follows. See also the working example at https://jsfiddle.net/nagix/xerdcm6z/.
```javascript
var chart = new Chart(/* ... */);

var pauseTime;

function pause() {
  var realtimeOpts = chart.options.scales.x.realtime;
  realtimeOpts.pause = true;
  chart.update('none');
  pauseTime = Date.now();
}

function resume() {
  var realtimeOpts = chart.options.scales.x.realtime;
  realtimeOpts.delay += Date.now() - pauseTime;
  realtimeOpts.pause = false;
  chart.update('none');
  pauseTime = undefined;
}
```
