### ISSUE TITLE
Please request this project as a new lib on cdnjs

### ISSUE THREAD

**Issue by kuofp** [nagix/chartjs-plugin-streaming#99]
This lib is awesome and it has reached 200 stars on GitHub([basic requirement on cdnjs](https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING.md#b-request-a-new-library)).

Please consider putting it on cdnjs which could improve the ecosystem of chartjs.

**Comment by nagix** [comment]
Closing as chartjs-plugin-streaming is now on [cdnjs](https://cdnjs.com/libraries/chartjs-plugin-streaming).
